### ISSUE TITLE
Add Python 3.9 testing on Linux

### ISSUE THREAD

**Issue by nedrebo** [zivid/zivid-python#107]
We should include a distro with  Python 3.9. Maybe Fedora 33 is an easy win if we base CI setup on the Fedora 30 work. It s nice to add more non-Ubuntus to increase the test surface of Zivid SDK.

_Originally posted by @nedrebo in https://github.com/zivid/zivid-python/pull/106#discussion_r543571633_

**Comment by eskaur** [comment]
Fedora33 with python3.9 is now part of the CI.
