### ISSUE TITLE
Camera intrinsics

### ISSUE THREAD

**Issue by IanYangChina** [zivid/zivid-python#108]
Hi,

I have gone through the zivid KnowledgeBase and noticed that the camera intrinsic parameters can be accessed from the zivid API. However I couldn't manage to find the corresponding API. Could you tell me where can I get these information? Thanks :)

>https://zivid.atlassian.net/wiki/spaces/ZividKB/pages/72450103/7.+Cautions+and+recommendations
> ...Each Zivid camera unit goes through an extensive calibration process, a part of which includes determining the intrinsic parameters of its 2D color camera. These parameters are available from the Zivid API. Therefore, it is beneficial to use a hand-eye calibration method that allows making use of these parameters...

**Comment by nedrebo** [comment]
Hi,

Intrinsics support is unfortunately not implemented in `zivid-python`.

A feature request for adding this is opened in https://github.com/zivid/zivid-python/issues/42. I'm closing this issue as a duplicate.
