### ISSUE TITLE
Undo PR #121 once actions/virtual-environments issue 2658 is fixed

### ISSUE THREAD

**Issue by knzivid** [zivid/zivid-python#122]
Track https://github.com/actions/virtual-environments/issues/2658

**Comment by eskaur** [comment]
Once this is all settled, would you recommend going back to "archlinux/base" or something else?

**Comment by knzivid** [comment]
Nah.. I would still stick to archlinux/archlinux. The whole point of arch is to keep rolling and directly using the images from archlinux upstream is better

**Comment by eskaur** [comment]
Aha, so will revert from `archlinux/archlinux:base-devel` to `archlinux/archlinux:base` when resolving this issue.

**Comment by knzivid** [comment]
We were originally on the docker hub packaged `archlinux` but we switched now to `archlinux/archlinux`. The reason why we switched to `base-devel` tag is that we build AUR packages and

> base-devel is a package group that includes tools needed for building (compiling and linking). It is not necessary for a basic install, and many users don't need to install it. If you find it useful, you can either install it as part of your basic install, or later.

**Comment by eskaur** [comment]
Resolved by https://github.com/zivid/zivid-python/pull/125
