### ISSUE TITLE
Failed to import zivid module

### ISSUE THREAD

**Issue by AnasIbrahim** [zivid/zivid-python#127]
I'm using 2.3 SDK and installed the module from source. It builds successfully but fail when imported.

Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zivid
Traceback (most recent call last):
  File "/home/iiwa/.local/lib/python3.8/site-packages/_zivid/__init__.py", line 35, in <module>
    from _zivid._zivid import (  # pylint: disable=import-error,no-name-in-module
ModuleNotFoundError: No module named '_zivid._zivid'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iiwa/.local/lib/python3.8/site-packages/zivid/__init__.py", line 8, in <module>
    import zivid.firmware
  File "/home/iiwa/.local/lib/python3.8/site-packages/zivid/firmware.py", line 2, in <module>
    import _zivid
  File "/home/iiwa/.local/lib/python3.8/site-packages/_zivid/__init__.py", line 73, in <module>
    raise ImportError(__missing_sdk_error_message()) from ex
ImportError: Failed to import the Zivid Python C-module, please verify that:
 - Zivid SDK is installed
 - Zivid SDK version is matching the SDK version part of the Zivid Python version 

I was thinking about downgrading to 2.1 but not sure if Zivid Two works with it.

**Comment by eskaur** [comment]
Hi @AnasIbrahim , thank you for reaching out to us.

Some questions to start:
- Can you confirm the exact version of your Zivid SDK installation? One way to do this is to open Zivid Studio and go to "Help -> About Zivid Studio". Either type in the whole version string or just take a screenshot of the pop up window.
- What operating system are you on? I see that it is Linux, but I don't know which distro.
- Can you give me the exact series of commands that you use to build/install zivid-python?

You are correct that SDK 2.1 would not work with a Zivid Two.

**Comment by eskaur** [comment]
Actually, I see now that this problem has also appeared in our test-pipeline,
https://github.com/zivid/zivid-python/actions 
so we have a reproducer. We will look into this immediately.

**Comment by eskaur** [comment]
Fix is now merged and released. You can either use latest `master` branch or do a `python3 -m pip install --upgrade zivid`.
Let us know if it works out for you. If it does, you can close this issue.

**Comment by AnasIbrahim** [comment]
Yes, It works now. Thanks for the very quick fix.
