### ISSUE TITLE
Usage error when install Zivid SDK

### ISSUE THREAD

**Issue by trym-b** [zivid/zivid-python#14]
When we are installing Zivid SDK's debian packages on Ubuntu, we do not set the correct permissions. The temporary directory in 
`function install_www_deb`
should have an additional line:
`chmod 775 "$TMP_DIR" || exit $?`
immediately after creating the directory

**Comment by nedrebo** [comment]
The result of this error can be seen as a warning or error depending on Ubuntu version:

`N: Download is performed unsandboxed as root as file '/tmp/zivid-python-install-www-deb-BqOy/zivid_1.7.0+a115eaa4-4_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
`

**Comment by eskaur** [comment]
Is this still an issue, @trym-b ?

**Comment by nedrebo** [comment]
Fixed in https://github.com/zivid/zivid-python/commit/7ddf591ba6fc7ee49ef5fef3088603720ba21d1f, this bug was silent in 16.04, warning in 18.04 and error in 20.04. Since we now support 20.04 this is no longer a problem.
