### ISSUE TITLE
Cannot install on Ubuntu 20.04 with python 3.7.9

### ISSUE THREAD

**Issue by TommasoBendinelli** [zivid/zivid-python#182]
Hello, when doing` pip install zivid` I am getting the following error:
` && /usr/bin/c++ -fPIC -O3 -DNDEBUG  -flto -shared  -o src/_zivid.cpython-37m-x86_64-linux-gnu.so src/CMakeFiles/_zivid.dir/Calibration/Calibration.cpp.o src/CMakeFiles/_zivid.dir/Calibration/Detector.cpp.o src/CMakeFiles/_zivid.dir/Calibration/HandEye.cpp.o src/CMakeFiles/_zivid.dir/Calibration/MultiCamera.cpp.o src/CMakeFiles/_zivid.dir/Calibration/Pose.cpp.o src/CMakeFiles/_zivid.dir/CaptureAssistant.cpp.o src/CMakeFiles/_zivid.dir/DataModel.cpp.o src/CMakeFiles/_zivid.dir/Firmware.cpp.o src/CMakeFiles/_zivid.dir/InfieldCorrection/InfieldCorrection.cpp.o src/CMakeFiles/_zivid.dir/NodeType.cpp.o src/CMakeFiles/_zivid.dir/ReleasableArray2D.cpp.o src/CMakeFiles/_zivid.dir/ReleasableCamera.cpp.o src/CMakeFiles/_zivid.dir/ReleasableFrame.cpp.o src/CMakeFiles/_zivid.dir/ReleasableFrame2D.cpp.o src/CMakeFiles/_zivid.dir/ReleasableImage.cpp.o src/CMakeFiles/_zivid.dir/ReleasablePointCloud.cpp.o src/CMakeFiles/_zivid.dir/SingletonApplication.cpp.o src/CMakeFiles/_zivid.dir/Version.cpp.o src/CMakeFiles/_zivid.dir/Wrapper.cpp.o -L/home/tommaso/.conan/data/pybind11/2.9.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib -Wl,-rpath,/home/tommaso/.conan/data/pybind11/2.9.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib:  /usr/lib/libZividCore.so  /home/tommaso/.pyenv/versions/3.7.9/lib/libpython3.7m.a  -lcrypt  -lpthread  -ldl  -lutil  -lm && :
  /usr/bin/ld: /home/tommaso/.pyenv/versions/3.7.9/lib/libpython3.7m.a(abstract.o): relocation R_X86_64_PC32 against symbol `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC`

Any idea?

Best

**Comment by eskaur** [comment]
Which C++ compiler (with version) do you have?

**Comment by TommasoBendinelli** [comment]
Solved, I was missing  python3-dev
