### ISSUE TITLE
the python api doesnt work straight a way

### ISSUE THREAD

**Issue by Hanjinchao** [zivid/zivid-python#213]
I am using windows 10, the zivid studio is working 
I had python3.74 and pip installed zivid api, then I copied example code from the readme but I got this error message:

`ImportError: cannot import name 'Application' from 'zivid' `
or 
```
app = zivid.Application()
AttributeError: module 'zivid' has no attribute 'Application'
```

**Comment by eskaur** [comment]
Can I see the entire code of the script you are running to test this?

**Comment by Hanjinchao** [comment]
```
import zivid 
# from zivid import Application, Settings
app = zivid.Application()
```

this is the message:

Traceback (most recent call last):
  File "c:/Users/../Documents/scaner_test/zivid.py", line 1, in <module>
    import zivid 
  File "c:\Users\..\Documents\scaner_test\zivid.py", line 3, in <module>
    app = zivid.Application()
AttributeError: module 'zivid' has no attribute 'Application'
PS C:\Users\..\Documents\scaner_test>

**Comment by Hanjinchao** [comment]
PS C:\Users\..\Documents\scaner_test> pip install zivid
Requirement already satisfied: zivid in c:\python\python37\lib\site-packages (2.8.0.2.9.0)
Requirement already satisfied: numpy in c:\python\python37\lib\site-packages (from zivid) (1.21.6)

**Comment by eskaur** [comment]
Aha, I think you have a naming conflict because you also have a file called `zivid.py`. So when you do `import zivid` it imports your file instead of our package. Try renaming your `zivid.py` to something else.

**Comment by Hanjinchao** [comment]
yeah you right, that was a silly mistake, thanks a lot !!

**Comment by eskaur** [comment]
No problem. Thank you for closing the issue.
