### ISSUE TITLE
Mismatching Serial number

### ISSUE THREAD

**Issue by suahelen** [zivid/zivid-python#235]
Hi 

I am using a zivid2 M70 from different sources (python, c# and zivid studio) 
I have run into some issues here, when I want to use any SDK version higher than 2.7.0. When using v2.7.0 or below everything runs fine.

I get the error message:
Error: Using default carbon IP and ports returned mismatching serial number 2136EB5F. Expected serial number 2042B54A.

This error renders also the frimware updater useless. I cannot access the camera from code or Zivid studio.
From all of these tools I get the same error. 

Do you have any suggestions as to what might be the problem here?

**Comment by eskaur** [comment]
Hi!
Are you sure you only have one Zivid camera connected?

**Comment by eskaur** [comment]
Something to try while I investigate internally:

1. Factory reset: https://support.zivid.com/en/latest/reference-articles/factory-reset-button-zivid-two.html
2. (if default IP address does not work for you) Configure static IP: https://support.zivid.com/en/latest/getting-started/software-installation/network-configuration/static-network-configuration-camera.html

**Comment by suahelen** [comment]
Yes, I am sure that there is only one camera. Here also the output of the ZividListCameras.exe (SDK v2.7.0):
```
Found 1 camera(s).
{ Camera info: { Model: zividTwo, Model Name: Zivid Two, Serial Number: xxxxxxxx, Hardware Revision: 4.2, Firmware Version: 1.7.4+97c05d67, USB Path: , Network Path: 172.28.60.5, Internal camera id: xxxxxxxxxxxx, Projector firmware tag:  } }
```
If I use a higher sdk, the ZividListCameras.exe returns the same error. In zivid Studio I can only see one camera, but the serial number has changed.

I have the port configured to be static with ip=172. 28.60.2 and subnet mask=255.255.255.0
I can try a factory reset.

**Comment by eskaur** [comment]
Q: Which of the two serial numbers in the error message match the camera you have? 
Q: Did it actually print "Serial Number: xxxxxxxx" or did you change that before pasting somehow?

2042B54A appears to be a very early engineering sample of the Zivid Two. 2136EB5F is production-grade.

**Comment by suahelen** [comment]
that was silly me. 

that is the actual printout:
```
Found 1 camera(s).
{ Camera info: { Model: zividTwo, Model Name: Zivid Two, Serial Number: 2136EB5F, Hardware Revision: 4.2, Firmware Version: 1.7.4+97c05d67, USB Path: , Network Path: 172.28.60.5, Internal camera id: 4C4BF980064C, Projector firmware tag:  } }
```

**Comment by eskaur** [comment]
**Can you try deleting your `Camera.yml` config file if you have one?** This file should no longer be necessary with SDK 2.8.0 and later.

Location:

- Linux: `~/.config/Zivid/API/`
- Windows: `%LOCALAPPDATA%\Zivid\API\`


https://support.zivid.com/en/latest/getting-started/software-installation/zivid-two-network-configuration.html#cameras-yml-and-how-to-restrict-discoverable-cameras

**Comment by eskaur** [comment]
SDK 2.8.0 introduced automatic discovery of network cameras. I suspect that you are now discovering some other camera on the network (2042B54A), which is conflicting with your own camera somehow. With SDK 2.7.0 that other camera was probably not discovered.

**Comment by suahelen** [comment]
Hmm I cannot find any such file. Actually there is no such file on the entire system. I was looking for it with (voidtools Everything)

**Comment by suahelen** [comment]
Direct cable to a PCIE network card.

**Comment by eskaur** [comment]
Can you try disconnecting all other network cables (such as the office network / internet) and then try with the new SDK again?

**Comment by suahelen** [comment]
I tried a factory reset and disconnected/disabled all network ports except the one for the zivid (pcie card) and internet (which is on the mainboard, which I need as I am working remotely) 
Unfortunately nothing improved.

**Comment by eskaur** [comment]
Even after disconnecting everything else, you still got an error message that mentions another camera with serial number "2042B54A"?

**Comment by suahelen** [comment]
So I found out something interesting:
Apparently one can use the ZividNetworkCameraConfigurator.exe to do the firmware update as well. But since it works by selection IP or Hostname I was able to do a firmware update from SDK v2.9.0. (and v2.10.0) 
Funny enough, after  that I had 2 cameras showing up. One with SN: 2136EB5F  and the other with SN: 2042B54A 
I was then able to connect to the first one.
I then switched back to SDK v2.7.0 where only one camera (2136EB5F ) was found again.
Going to the newer SDK again resulted in the same behaviour as before

here the ouputs of the ZividListCameras.exe:
SDK v2.9.0
```
C:\Program Files\Zivid\bin>ZividListCameras.exe
Found 2 camera(s).
{ Camera info: { Model: zividTwo, Model Name: Zivid Two, Serial Number: 2136EB5F, Hardware Revision: 4.2, Firmware Version: 1.14.7+faaa47ed, Network Path: 172.28.60.5, Internal camera id: 4C4BF980064C, Projector firmware tag:  } }
Error: Failed to make a socket connection to 172.28.60.5:52811

End of file

[asio.misc:2]

```
SDK v2.7.0
```
C:\Program Files\Zivid\bin>ZividListCameras.exe
Found 1 camera(s).
{ Camera info: { Model: zividTwo, Model Name: Zivid Two, Serial Number: 2136EB5F, Hardware Revision: 4.2, Firmware Version: 1.7.4+97c05d67, USB Path: , Network Path: 172.28.60.5, Internal camera id: 4C4BF980064C, Projector firmware tag:  } }
```

**Comment by suahelen** [comment]
> Even after disconnecting everything else, you still got an error message that mentions another camera with serial number "2042B54A"?

Yes that was still the case

**Comment by suahelen** [comment]
Just to summarise: 
by using:
`ZividNetworkCameraConfigurator.exe get-config 172.28.60.5 --update-firmware`
I was able to update the Firmware of the camera to a  SDK version  > 2.7.0. After that I find two cameras, even though still only one is connected. But I am able to connect to the correct one. For the second one the issue persists. 

For me this solves the issue. 
Thanks for the quick help.
  Cheers

**Comment by eskaur** [comment]
Glad it worked out for you!

Sorry for the hassle. Improving the simplicity of network camera setup is on our roadmap :)
