### ISSUE TITLE
Break and Trace Error

### ISSUE THREAD

**Issue by hai-h-nguyen** [zivid/zivid-python#282]
Hi,

I got this error whenever calling the transform function to transform the point cloud to another coordinate. I tried to use different sdk versions but still the same error. Mine is Ubuntu 22.04.

**Comment by johningve** [comment]
Hi!

Would you be able to provide more detail on the error that you got?

**Comment by hai-h-nguyen** [comment]
Never mind, somehow it works today.

**Comment by johningve** [comment]
I'm happy to hear that it works for you now. Let us know if this issue comes up again in the future!
