### ISSUE TITLE
CMake not found error during pip install even though cmake is available

### ISSUE THREAD

**Issue by kohei-furukawa22** [zivid/zivid-python#300]
While building a Dcoker container, an error occurs in the following environment when pip install zivid is executed in the Dockerfile.
The same error occurs when building a container without installing zivid-python and executing wget or later commands in the container.
I can run the 'cmake --version' command inside the container.

Last month the build was successful, but when I tried it yesterday, this is the result.
Can you please tell me the cause and solution for this?

*** Dcokerfile ***
      
      FROM ubuntu:22.04
      ENV DEBIAN_FRONTEND noninteractive
      
      RUN apt update
      RUN apt install -y wget cmake
      RUN apt install -y python3 python3-dev python3-pip
      
      RUN mkdir Zivid
      WORKDIR /Zivid
      RUN wget \ 
      　　https://downloads.zivid.com/sdk/releases/2.11.1+de9b5dae-1/u22/zivid_2.11.1+de9b5dae-1_amd64.deb \ 
      　　https://downloads.zivid.com/sdk/releases/2.11.1+de9b5dae-1/u22/zivid-telicam-driver_3.0.1.1-3_amd64.deb \ 
      　　https://downloads.zivid.com/sdk/releases/2.11.1+de9b5dae-1/u22/zivid-studio_2.11.1+de9b5dae-1_amd64.deb \ 
      　　https://downloads.zivid.com/sdk/releases/2.11.1+de9b5dae-1/u22/zivid-tools_2.11.1+de9b5dae-1_amd64.deb \ 
      　　https://downloads.zivid.com/sdk/releases/2.11.1+de9b5dae-1/u22/zivid-genicam_2.11.1+de9b5dae-1_amd64.deb
      RUN apt update && apt install -y ./*.deb
      RUN python3 -m pip install -U pip && python3 -m pip install conan
      RUN python3 -m pip install -U pip && python3 -m pip install zivid==2.11.1.2.11.1

***Error message ***

      .....
      Step 11/11 : RUN python3 -m pip install -U pip && python3 -m pip install zivid==2.11.1.2.11.1
      ---> Running in 18f8ccb50d01
      Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (24.3.1)
      WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
      Collecting zivid==2.11.1.2.11.1
        Downloading zivid-2.11.1.2.11.1.tar.gz (78 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        x exit code: 1
        mq> [37 lines of output]
            Traceback (most recent call last):
              File "<string>", line 75, in run_process
            RuntimeError: Wait failed with exit code -11
      
            The above exception was the direct cause of the following exception:
      
            Traceback (most recent call last):
              File "<string>", line 82, in _check_cpp17_compiler
              File "<string>", line 79, in run_process
            RuntimeError: Process failed: 'cmake --version'.
      
      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-pi44coz_/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-pi44coz_/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-pi44coz_/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-pi44coz_/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 156, in <module>
        File "<string>", line 122, in _main
        File "<string>", line 84, in _check_cpp17_compiler
      RuntimeError:
      
            +-----------------------+
            | !! CMake not found !! |
            +-----------------------+
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      x exit code: 1
      mq> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      Removing intermediate container 18f8ccb50d01
      The command '/bin/sh -c python3 -m pip install -U pip && python3 -m pip install zivid==2.11.1.2.11.1' returned a non-zero code: 1

**Comment by johningve** [comment]
Hi, can you try upgrading pip to the latest version before installing zivid-python and see if that resolves the issue?

**Comment by kohei-furukawa22** [comment]
Thanks for the reply.
I'm already using the latest version of pip (24.3.1).
I have tried again with the following fixes and am getting the same error.

`#  RUN python3 -m pip install -U pip && python3 -m pip install zivid==2.11.1.2.11.1`
`#  ↓ fix  ↓`
`RUN python3 -m pip install -U pip`
`RUN python3 -m pip install zivid==2.11.1.2.11.1`

**Comment by vawale** [comment]
Hi, I couldn't reproduce the issue using the docker file contents you mentioned. I have a docker test image using the contents of your Docker file here - https://hub.docker.com/r/vawale/test_zivid_py_in_docker 

Can you try out if this test image works for you?

```sh
docker pull vawale/test_zivid_py_in_docker
```

**Comment by kohei-furukawa22** [comment]
The test image was successfully built and the container could be run.
I also run pip list and verified that zivid ver-2.11.1.2.11.1 was installed.

**Comment by vawale** [comment]
> Thank you for your response. The test image was successfully built and the container could be run. I also run pip list and verified that zivid ver-2.11.1.2.11.1 was installed.

The image was built using the Dockerfile you pasted in the issue. I built this image on ubuntu 24.04, docker version `Docker version 26.1.3, build 26.1.3-0ubuntu1~24.04.1`. Which platform and docker version do you use to build image on your system? 

Another thing to try is not installing `cmake` from apt. Since zivid-python ends up installing `cmake` as a dependency from `pip`, you end up having potentially two versions, one installed from apt and one from pip. Also, you install `zivid-python` system wide, which means the cmake from pip also gets installed system wide.

**Comment by kohei-furukawa22** [comment]
I tried the method of not apt intall cmake and that solved the problem.

Note that when I solved this problem, the version of the image was built with `Ubuntu-22.04.4` , `docker 24.0.7 Ubuntu-20.04.5` was used at build time.

Thank you for your support in resolving this issue.
