### ISSUE TITLE
Nightly build test released python package

### ISSUE THREAD

**Issue by trym-b** [zivid/zivid-python#34]
The current nightly tests only tests the tip of master, which is a good thing, but we should also add a test that tests the actually released pip package.
The procedure should be something like:

```
Install latest SDK
Install zivid-python dependency (python, C++ compiler)
Run pip install zivid
Run tests/samples
```

**Comment by nedrebo** [comment]
This will not work. New test are added that test functionality not yet released to pip will fail.

**Comment by trym-b** [comment]
> This will not work. New test are added that test functionality not yet released to pip will fail.

Some tests yes, I was referring to different tests than the one in today's test directory. We could probably run all tests that are not part of the commit group that is the difference between top of master and the latest release commit.

**Comment by nedrebo** [comment]
What the goal of this test, what kind of error do you want to target?

When uploaded to pypi the package is per definition tested and ok. If we are not certain about that we should improve the testing before uploading.

As I see it the proposed test will only test for external errors.

**Comment by trym-b** [comment]
The goal is to detect mismatches between the released pip package vs the released SDK.

**Comment by nedrebo** [comment]
Understand, then I would keep it simple and add a test for just that. Use pip to find latest version from pypi, download http://www.zivid.com/hubfs/softwarefiles/latest_version and compare. Open a new issue about this idea.
