### ISSUE TITLE
Update default 2D API sample settings

### ISSUE THREAD

**Issue by torbsorb** [zivid/zivid-python#45]
The default settings (Iris 50, exposure 50ms) are not ideal I believe. I would like to see a much lower Iris (maybe 21?) and lower exposure (maybe 10000?).

@theie @SatjaSivcev

**Comment by SatjaSivcev** [comment]
I agree with lowering the iris and the exposure time. We can crank up the gain for 2D to compensate for the exposure. Brightness can be 1.8 as well. The resulting image should be reasonably well exposed, i.e. not dark and not saturated for e.g. M camera at 1m with a common scene.

**Comment by eskaur** [comment]
When you say "default" you mean the settings in `sample_capture_2d.py`, right?

I totally agree that those settings are silly. The C++ sample has t=10ms and iris=35, which is much more reasonable. We may want to avoid b=1.8 though, since the won't work on Amber, right? 
@SatjaSivcev @torbsorb

**Comment by SatjaSivcev** [comment]
Good catch about Amber. Yes that is what I meant as 'default'. The point is that we want meaningful settings that are chosen for a particular reason. I can test when I get a camera in my hands.

**Comment by eskaur** [comment]
Alright. Feel free to make a PR with the new settings, or just post them here and we can follow up when we have time.

**Comment by SatjaSivcev** [comment]
I think this can be closed @torbsorb? See: https://github.com/zivid/zivid-python/commit/f1d25002d391969e74fd234fea57b832ad421198

**Comment by torbsorb** [comment]
Yes, it has been resolved.
