### ISSUE TITLE
Module names are inconsitent

### ISSUE THREAD

**Issue by trym-b** [zivid/zivid-python#47]
The current `zivid` module names are inconsistent, we are using both snake case and lower case without separators. For example `captureassistant` and `camera_state`. These should all be proper snake case.

A quick fix could be to simply rename all the modules to proper snake case, but we should instead implement a camelCase to snake_case function in the pybind11 layer, so that we can simply do a one-to-one mapping of the `_zivid` modules to `zivid` modules

**Comment by nedrebo** [comment]
I think we should go straight for the proper solution to avoid tech debt.

The fix should be to replace the `tolower` here with a transform from capital case to snake case here:

https://github.com/zivid/zivid-python/blob/b52396668cd60c285d1e1ac6f7748e5c93fb740b/src/include/ZividPython/Wrappers.h#L52-L60

The same transform should also be applied in `wrapClass` and `wrapEnum`

**Comment by kontramind** [comment]
Would ti be possible to have test(s) to check if the name transformation is working - or it would be considered as over-engineering?

**Comment by trym-b** [comment]
Perhaps we could add that, although we have not set up a C++ test framework for this repository so it might be a bit too much work at this moment.

**Comment by eskaur** [comment]
This one is fixed now, right? @trym-b

**Comment by trym-b** [comment]
Right, will close it.
