### ISSUE TITLE
Modules names are incorrect in samples

### ISSUE THREAD

**Issue by alexey-kashapov** [zivid/zivid-python#50]
in **sample_capture_assistant.py** you used incorrect name e.g. importing here:
`from zivid.capture_assistant import AmbientLightFrequency, SuggestSettingsParameters`
please change it to zivid.captureassistant

**Comment by trym-b** [comment]
We changed the naming of the submodules under `zivid`, but we have not made a release with these changes just yet. The correct naming going forward is `capture_assistant`, not `captureassistant`

In the meantime you can work around this by either:
1. rename `capture_assistant` to `capture_assistant` when installing zivid-python through `pip install zivid`
or
2. install zivid-python through `pip install .` after cloning this repository. This way you will have all the latest changes (including the module name changes) and can use the samples right out of the box.

**Comment by trym-b** [comment]
New pip package has just been released.
`pip install zivid` should now work with `import zivid.capture_assistant`

Closing this issue.

**Comment by alexey-kashapov** [comment]
nice! thank you!
