### ISSUE TITLE
pip install zivid not working on Python 3.8 (Please Help)

### ISSUE THREAD

**Issue by zeelbhatt** [zivid/zivid-python#52]
Collecting zivid
  Using cached https://files.pythonhosted.org/packages/a5/a7/32e08e5609535b08e23e8f2ae6620f832bdaa2882573777b17fc5a9139ea/zivid-1.0.0.1.8.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy (from zivid)
  Using cached https://files.pythonhosted.org/packages/0e/c3/be53614c4e3490778050e1df48fd463837297d5dd402dae3b500f2050eba/numpy-1.18.1-cp38-cp38-win32.whl
Building wheels for collected packages: zivid
  Building wheel for zivid (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\nuvoemb01\appdata\local\programs\python\python38-32\python.exe' 'c:\users\nuvoemb01\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\NUVOEM~1\AppData\Local\Temp\tmpj3q29v4d'
       cwd: C:\Users\NuvoEmb01\AppData\Local\Temp\pip-install-gt7qv3g4\zivid
  Complete output (67 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 8.2.0
  -- Check for working C compiler: C:/MinGW/bin/gcc.exe
  -- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 8.2.0
  -- Check for working CXX compiler: C:/MinGW/bin/c++.exe
  -- Check for working CXX compiler: C:/MinGW/bin/c++.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/NuvoEmb01/AppData/Local/Temp/pip-install-gt7qv3g4/zivid/_cmake_test_compile/build
  -- The CXX compiler identification is GNU 8.2.0
  -- Check for working CXX compiler: C:/MinGW/bin/c++.exe
  -- Check for working CXX compiler: C:/MinGW/bin/c++.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
  CMake Error at CMakeLists.txt:12 (conan_cmake_run):
    Unknown CMake command "conan_cmake_run".

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/NuvoEmb01/AppData/Local/Temp/pip-install-gt7qv3g4/zivid/_skbuild/win32-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
    File "C:\Users\NuvoEmb01\AppData\Local\Temp\pip-build-env-f62o0qdw\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 570, in setup
      env = cmkr.configure(cmake_args,
    File "C:\Users\NuvoEmb01\AppData\Local\Temp\pip-build-env-f62o0qdw\overlay\Lib\site-packages\skbuild\cmaker.py", line 221, in configure
      raise SKBuildError(

   Trying "Ninja (Visual Studio 15 2017 v141)" generator

   Trying "Ninja (Visual Studio 15 2017 v141)" generator - success

  Traceback (most recent call last):

  An error occurred while configuring with CMake.
    Command:
      "cmake" "C:\Users\NuvoEmb01\AppData\Local\Temp\pip-install-gt7qv3g4\zivid" "-G" "Ninja" "-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\NuvoEmb01\AppData\Local\Temp\pip-install-gt7qv3g4\zivid\_skbuild\win32-3.8\cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=c:\users\nuvoemb01\appdata\local\programs\python\python38-32\python.exe" "-DPYTHON_VERSION_STRING:STRING=3.8.2" "-DPYTHON_INCLUDE_DIR:PATH=c:\users\nuvoemb01\appdata\local\programs\python\python38-32\Include" "-DPYTHON_LIBRARY:FILEPATH=c:\users\nuvoemb01\appdata\local\programs\python\python38-32\libs\python38.lib" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=C:\Users\NuvoEmb01\AppData\Local\Temp\pip-build-env-f62o0qdw\overlay\Lib\site-packages\skbuild\resources\cmake" "-DZIVID_PYTHON_VERSION=1.0.0.1.8.0" "-DZIVID_SDK_VERSION=1.8.0" "-DCMAKE_BUILD_TYPE:STRING=Release"
    Source directory:
      C:\Users\NuvoEmb01\AppData\Local\Temp\pip-install-gt7qv3g4\zivid
    Working directory:
      C:\Users\NuvoEmb01\AppData\Local\Temp\pip-install-gt7qv3g4\zivid\_skbuild\win32-3.8\cmake-build
  Please see CMake's output for more information
  ERROR: Failed building wheel for zivid
  Running setup.py clean for zivid
Failed to build zivid
ERROR: Could not build wheels for zivid which use PEP 517 and cannot be installed directly

**Comment by zeelbhatt** [comment]
I have checkd all Dependencies :
Python version 3.5 or higher
Zivid SDK version 1.8.0 or higher
Compiler with C++17 support

**Comment by nedrebo** [comment]
Thanks for the report. We will look into this this. As a workaround, if possible, you can use Python 3.7 which have pre-compiled binaries available. Then you avoid all the compilation issues you are seeing.

**Comment by nedrebo** [comment]
@trym-b / @eskaur: We should provide 3.8 binaries as well when releasing the next version. FYI

**Comment by zeelbhatt** [comment]
Thank you for your help

**Comment by eskaur** [comment]
@zeelbhatt : We officially support Python 3.6, 3.7, 3.8 and 3.9 in the latest version. Please let us know if you have any more issues.
Closing this issue as I think it's resolved.
