### ISSUE TITLE
Change Ambient Light Frequency to None in sample_capture_assistant.py

### ISSUE THREAD

**Issue by SatjaSivcev** [zivid/zivid-python#55]
We should be consistent in samples across different programming languages.
The C++ one uses none:
https://github.com/zivid/zivid-sdk/blob/bf89ba7cce266c1fa02a97fa26cd2d72b2620888/cpp/Samples/CPP/SampleCaptureAssistant.cpp#L20
The C# one uses none:
https://github.com/zivid/zivid-sdk/blob/bf89ba7cce266c1fa02a97fa26cd2d72b2620888/cpp/Samples/Csharp/SampleCaptureAssistant.cs#L17
The Python one uses 50Hz:
https://github.com/zivid/zivid-python/blob/0c13385e884cb7a763e6056f74b00760b5f78b20/samples/sample_capture_assistant.py#L13

**Comment by nedrebo** [comment]
Feel free to open PRs instead of issues for trivial changes. I think that will be more efficient for both parts. Issues like this are unlikely to get top priority by us and it will usually take long time before addressed.
