### ISSUE TITLE
Change iris valeus to 14,21,35 in capture_hdr.py

### ISSUE THREAD

**Issue by SatjaSivcev** [zivid/zivid-python#56]
https://github.com/zivid/zivid-python/blob/0c13385e884cb7a763e6056f74b00760b5f78b20/samples/sample_capture_hdr.py#L10-L12

Currently, iris values in use are 20, 30, 60. For most common dynamic range coverage we should use 14, 21, 35. This is in line with Zivid Academy: https://zivid.atlassian.net/wiki/spaces/ZividKB/pages/99844206/Getting+the+right+exposure+for+good+point+clouds

**Comment by nedrebo** [comment]
Feel free to open PRs instead of issues for trivial changes. I think that will be more efficient for both parts. Issues like this are unlikely to get top priority by us and it will usually take long time before addressed.

**Comment by SatjaSivcev** [comment]
@nedrebo I don't have permision to create a branch in this repo. Can I get it?

![image](https://user-images.githubusercontent.com/46567886/76658229-055a2300-654a-11ea-97a0-f5d24cd0acca.png)

**Comment by nedrebo** [comment]
I added your team.

(When you don't have access to create branches in a public repository you can still always make a *fork*  and a PR back into the main repository.)
