### ISSUE TITLE
Modify sample_capture_2d.py

### ISSUE THREAD

**Issue by SatjaSivcev** [zivid/zivid-python#57]
https://github.com/zivid/zivid-python/blob/master/samples/sample_capture_2d.py#L10-L12
Add brightness and gain like in C++:
https://github.com/zivid/zivid-sdk/blob/bf89ba7cce266c1fa02a97fa26cd2d72b2620888/cpp/Samples/CPP/SampleCapture2D.cpp#L16-L19
Also, use the same parameter values.

**Comment by nedrebo** [comment]
Feel free to open PRs instead of issues for trivial changes. I think that will be more efficient for both parts. Issues like this are unlikely to get top priority by us and it will usually take long time before addressed.
